name: movie_app_with_ci
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.0
  kiwi: ^4.1.0
  meta: ^1.9.1
  mocktail: ^1.0.3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  kiwi_generator: ^4.1.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

assets:
  - .env
